// @ts-check

import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import linguilint from 'eslint-plugin-lingui';

export default tseslint.config(
  // Local checkout of the upstream ADEME data, not part of the project.
  { ignores: ['impactco2/'] },
  // Catalogs generated by "npm run i18n-compile" start with a blanket
  // eslint-disable that triggers the unused-directive warning.
  { files: ['locales/*/messages.ts'], linterOptions: { reportUnusedDisableDirectives: 'off' } },
  eslint.configs.recommended,
  tseslint.configs.recommended,
  linguilint.configs['flat/recommended']
);