import { t } from "@lingui/core/macro";
import ademeCategories from "../data/ademe/0-categories.json";
import { alimentation } from "../data/ademe/categories/alimentation";
import { boissons } from "../data/ademe/categories/boisson";
import { casPratiques } from "../data/ademe/categories/caspratiques";
import { chauffage } from "../data/ademe/categories/chauffage";
import { deplacements } from "../data/ademe/categories/deplacement";
import { electromenager } from "../data/ademe/categories/electromenager";
import { fruitsEtLegumes } from "../data/ademe/categories/fruitsetlegumes";
import { habillements } from "../data/ademe/categories/habillement";
import { mobiliers } from "../data/ademe/categories/mobilier";
import { numeriques } from "../data/ademe/categories/numerique";
import { repas } from "../data/ademe/categories/repas";
import transportDistances from "../data/transport-distances.json";
import {
  AdemeCategory,
  AdemeECV,
  FootprintDetails,
  RawEquivalent,
} from "../types/AdemeECV";
import { Locale } from "../types/i18n";
import { Item } from "../types/item";

interface AdemeLocale {
  names: { [slug: string]: string };
  hypothesis: {
    pre: { [slug: string]: string };
    post: { [slug: string]: string };
  };
  ecv: { [id: string]: string };
}

// fr/en/es are generated by scripts/update-ademe-data.mjs; German is not
// translated upstream and de.json is maintained by hand in this repository.
// Each file is its own chunk: only the active locale's is ever downloaded.
const localeImports: {
  [L in Locale]: () => Promise<{ default: AdemeLocale }>;
} = {
  en: () => import("../data/ademe/locales/en.json"),
  fr: () => import("../data/ademe/locales/fr.json"),
  es: () => import("../data/ademe/locales/es.json"),
  de: () => import("../data/ademe/locales/de.json"),
};

let localeData: AdemeLocale | null = null;

// Must have completed before any other function of this module is called:
// components/app.tsx starts it at boot and suspends until it resolves.
export async function loadLocaleData(locale: Locale): Promise<void> {
  localeData = (await localeImports[locale]()).default;
}

function data(): AdemeLocale {
  if (localeData === null) {
    throw new Error("loadLocaleData() has not completed yet");
  }
  return localeData;
}

// Transports are declined in many variants upstream (city car, sedan...):
// only the ones with a defined journey length enter the game.
function flattenTransports(equivalents: RawEquivalent[]): RawEquivalent[] {
  const flattened = equivalents.flatMap((equivalent) =>
    equivalent.ecvs
      ? equivalent.ecvs.map((sub) => ({
          ...equivalent,
          ecvs: undefined,
          ecv: sub.ecv,
          slug: `${equivalent.slug}-${sub.subtitle}`
            .replace(/ /g, "")
            .toLowerCase(),
        }))
      : [equivalent],
  );
  const bySlug = new Map(
    flattened.map((equivalent) => [equivalent.slug, equivalent]),
  );
  const transports: RawEquivalent[] = [];
  for (const slug of Object.keys(transportDistances)) {
    const transport = bySlug.get(slug);
    if (transport) {
      transports.push(transport);
    } else {
      console.warn(`Transport "${slug}" is missing from the ADEME data`);
    }
  }
  return transports;
}

const rawDataByCategory: { [categoryId: number]: RawEquivalent[] } = {
  1: numeriques,
  2: [...alimentation, ...repas],
  3: boissons,
  4: flattenTransports(deplacements),
  5: habillements,
  6: electromenager,
  7: mobiliers,
  8: chauffage,
  9: fruitsEtLegumes,
  13: casPratiques,
};

const categories: Map<number, AdemeCategory> = new Map();
ademeCategories.data.forEach((category) =>
  categories.set(category.id, category),
);

// Items are computed on first access, once the lingui locale is active.
const itemsByLocale = new Map<Locale, Item[]>();
const itemsBySlugByLocale = new Map<Locale, Map<string, Item>>();

function getAllItems(locale: Locale): Item[] {
  let items = itemsByLocale.get(locale);
  if (!items) {
    items = [];
    for (const [categoryId, data] of Object.entries(rawDataByCategory)) {
      items.push(...computeItemsForCategory(Number(categoryId), data, locale));
    }
    itemsByLocale.set(locale, items);

    // Index by slug for direct lookups. Keep the first occurrence.
    const itemsBySlug = new Map<string, Item>();
    for (const item of items) {
      if (!itemsBySlug.has(item.source.slug)) {
        itemsBySlug.set(item.source.slug, item);
      }
    }
    itemsBySlugByLocale.set(locale, itemsBySlug);
  }
  return items;
}

const defaultItemSlugs = new Set([
  "smartphone",
  "television",
  "ordinateurportable",
  "repasavecduboeuf",
  "repasvegetarien",
  "repasavecdupoulet",
  "eauenbouteille",
  "vin",
  "laitdevache",
  "jeans",
  "tshirtencoton",
  "pullenlaine",
  "fourelectrique",
  "lavelinge",
  "refrigirateur",
  "chaiseenbois",
  "lit",
  "chauffagegaz",
  "chauffagefioul",
  "chauffageelectrique",
  "pompeachaleur",
  "avion-moyencourrier",
  "tgv",
  "voiturethermique",
  "voitureelectrique",
]);

export function getDefaultItems(locale: Locale): Item[] {
  return getAllItems(locale).filter((item) =>
    defaultItemSlugs.has(item.source.slug),
  );
}

export function getItemFromSlug(
  slug: string,
  locale: Locale,
): Item | undefined {
  getAllItems(locale);
  return itemsBySlugByLocale.get(locale)?.get(slug);
}

export function getCategories(): Map<number, AdemeCategory> {
  return categories;
}

export function getFootprintDetails(): FootprintDetails {
  return data().ecv;
}

export function getItemsFromCategoryId(
  categoryId: number,
  locale: Locale,
): Item[] {
  return getAllItems(locale).filter((item) => item.categoryId === categoryId);
}

// We have to make some computation on the data to make it better for users
// Functions below are only doing that

type ComputeItemFunc = (
  element: AdemeECV,
  coeff: number,
  locale: Locale,
) => { label: string; description: string; explanation: string };

function computeItemsForCategory(
  categoryId: number,
  data: RawEquivalent[],
  locale: Locale,
): Item[] {
  const computeItemFunc: ComputeItemFunc = getComputeFunction(categoryId);
  const items: Item[] = [];
  for (const raw of data) {
    const element = toAdemeECV(raw, locale);
    if (element === undefined) {
      continue;
    }
    const coeff = getCoefficient(categoryId, element);
    const source = withCoefficient(element, coeff);
    items.push({
      id: source.slug,
      categoryId: categoryId,
      source,
      ...computeItemFunc(source, coeff, locale),
    });
  }
  return items;
}

// Turns a raw impactco2 equivalent into the shape used by the game, resolving
// the translated name and hypothesis and computing the total footprint the
// same way impactco2 does (src/utils/computeECV.ts).
function toAdemeECV(raw: RawEquivalent, locale: Locale): AdemeECV | undefined {
  const name = getItemName(raw.slug);
  if (name === undefined) {
    console.warn(`No "${locale}" name for "${raw.slug}", skipping it`);
    return undefined;
  }

  const footprint = raw.ecv
    ? raw.ecv.reduce((sum, { value }) => sum + value, 0)
    : (raw.total ?? 0);
  const usage = raw.usage ? raw.usage.peryear * raw.usage.defaultyears : 0;

  const { hypothesis } = data();
  const hypothesisText = [hypothesis.pre[raw.slug], hypothesis.post[raw.slug]]
    .filter(Boolean)
    .join(" ");

  return {
    name,
    slug: raw.slug,
    ecv: footprint + usage + (raw.end ?? 0),
    footprint,
    footprintDetail: raw.ecv,
    usage: raw.usage,
    endOfLife: raw.end,
    months: raw.months,
    hypothesis: hypothesisText === "" ? undefined : hypothesisText,
    sources: raw.sources,
  };
}

// The names extracted from impactco2 are "quantified" ("kg de ;fraise",
// "smartphone[s]"): the part before ";" is a unit prefix and "[s]"/"[es]"/"[x]"
// are plural markers, both of which we drop.
function getItemName(slug: string): string | undefined {
  const name = data().names[slug];
  if (name === undefined) {
    return undefined;
  }
  const cleaned = name
    .split(";")
    .pop()!
    .replace(/\[(s|es|x)\]/g, "")
    .trim();
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
}

function getCoefficient(categoryId: number, element: AdemeECV): number {
  switch (categoryId) {
    case 4: // Transport: from 1km to a typical journey length
      return (transportDistances as { [slug: string]: number })[element.slug];
    case 8: // Heating: from 1m² to 60m², from 12 months to 1 month
      return 60 / 12;
    default:
      return 1;
  }
}

// Returns a scaled copy: the imported data objects are shared module state
// and must never be mutated.
function withCoefficient(element: AdemeECV, coeff: number): AdemeECV {
  const copy: AdemeECV = {
    ...element,
    ecv: element.ecv * coeff,
    footprintDetail: element.footprintDetail?.map((detail) => ({
      ...detail,
      value: detail.value * coeff,
    })),
    usage: element.usage ? { ...element.usage } : undefined,
  };
  if (copy.footprint !== undefined) {
    copy.footprint = copy.footprint * coeff;
  }
  return copy;
}

function getComputeFunction(categoryId: number): ComputeItemFunc {
  switch (categoryId) {
    case 1: // Digital
      return (element: AdemeECV) => {
        return {
          label: element.name,
          description: getDescriptionForDefaultYear(element),
          explanation: "",
        };
      };
    case 2: // Food
      return (element: AdemeECV) => {
        return {
          label:
            element.name + (element.slug.startsWith("repas") ? "" : " (1kg)"),
          description: "",
          explanation: "",
        };
      };
    case 3: // Drinks
      return (element: AdemeECV) => {
        return {
          label: element.name + " (1L)",
          description: "",
          explanation: "",
        };
      };
    case 4: // Transport
      return (element: AdemeECV, coeff: number) => {
        return {
          label: element.name + ` (${coeff}km)`,
          description: "",
          explanation: "",
        };
      };
    case 6: // Household appliance
    case 7: // Furnitures
      return (element: AdemeECV) => {
        return {
          label: element.name,
          description: getDescriptionForDefaultYear(element),
          explanation: "",
        };
      };
    case 8: // Heating
      return (element: AdemeECV) => {
        return {
          label: element.name,
          description: t`<strong>per month</strong> for 60m²`,
          explanation: t`Impact of one month of heating a house of 60m², spreading the consumption over the year.`,
        };
      };
    case 9: // Vegetables and fruits
      return (element: AdemeECV, _coeff: number, locale: Locale) => {
        return {
          label: element.name + " (1kg)",
          description: getSeasonDescription(element.months, locale),
          explanation: "",
        };
      };
    // case 10: // TODO Usage numérique needs more work
    default: // Clothing, practical cases
      return (element: AdemeECV) => {
        return {
          label: element.name,
          description: "",
          explanation: "",
        };
      };
  }
}

function getDescriptionForDefaultYear(element: AdemeECV) {
  let description = "";
  if (element.usage) {
    const defaultYears = element.usage.defaultyears;
    description = t`Purchase and usage for ${defaultYears} years.`;
  }
  return description;
}

function getSeasonDescription(
  months: number[] | undefined,
  locale: Locale,
): string {
  if (!months || months.length === 0) {
    return "";
  }
  if (months.length === 12) {
    return t`In season all year round`;
  }

  // Group consecutive months into ranges, merging December -> January.
  const sorted = [...new Set(months)].sort((a, b) => a - b);
  const ranges: number[][] = [[sorted[0]]];
  for (const month of sorted.slice(1)) {
    const range = ranges[ranges.length - 1];
    if (month === range[range.length - 1] + 1) {
      range.push(month);
    } else {
      ranges.push([month]);
    }
  }
  const first = ranges[0];
  const last = ranges[ranges.length - 1];
  if (ranges.length > 1 && first[0] === 0 && last[last.length - 1] === 11) {
    ranges[0] = [...last, ...first];
    ranges.pop();
  }

  const monthFormat = new Intl.DateTimeFormat(locale, { month: "long" });
  const monthName = (month: number) =>
    monthFormat.format(new Date(2000, month, 1));
  const season = ranges
    .map((range) =>
      range.length === 1
        ? monthName(range[0])
        : `${monthName(range[0])} – ${monthName(range[range.length - 1])}`,
    )
    .join(", ");
  return t`In season: ${season}`;
}
